# version: "3"
        
# services:  
#     # nginx
#     nginx:
#         container_name: ${APP_NAME}_nginx
#         build: ./docker-assets/nginx
#         volumes:
#             - ./:/var/www/myorder
#             - ./docker-assets/nginx/conf.d:/etc/nginx/conf.d
#         links:
#             - php-fpm
#         ports:
#             - 8080:8080
#         working_dir: /var/www/myorder
       
#     # php
#     php-fpm:
#         container_name: ${APP_NAME}_php-fpm
#         build: ./docker-assets/php
#         links:
#             - mysql
#         volumes:
#             - ./:/var/www/myorder
#         depends_on:
#             - mysql
#         working_dir: /var/www/myorder
        
#     # database
#     mysql:
#         container_name: ${APP_NAME}_mysql
#         image: mysql
#         volumes: 
#             - ./database:/var/lib/mysql
#         ports:
#             - 3306:3306
#         command: --default-authentication-plugin=mysql_native_password
#         restart: always
#         environment:
#             MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#             MYSQL_DATABASE: ${DB_DATABASE}
#             MYSQL_USER: ${DB_USERNAME}
#             MYSQL_PASSWORD: ${DB_PASSWORD}




version: '3.5'

services:
  ${APP_NAME}_app:
    build:
      context: './docker-assets/apache'
      args:
        uid: ${UID}
    container_name: ${APP_NAME}_app
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
    networks:
      backend:
        aliases:
          - ${APP_NAME}_app

  mysql-db:
    image: mysql
    container_name: ${APP_NAME}_mysql_db
    volumes:
      - ./run/var:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      backend:
        aliases:
          - db

networks:
  backend:
    name: backend-network